// client-svelte/src/external-resources/components/Footer.svelte
<script lang="ts">
  const currentYear = new Date().getFullYear();
</script>

<footer class="bg-background border-t border-border py-12">
  <div class="max-w-7xl mx-auto px-6 lg:px-8">
    <div class="flex flex-col md:flex-row justify-between items-center gap-8">
      <div class="flex flex-col items-center md:items-start gap-2">
        <div class="text-xl font-display font-bold" data-testid="text-footer-brand">
          Connect
        </div>
        <p class="text-sm text-muted-foreground text-center md:text-left" data-testid="text-footer-tagline">
          Real connections in the real world
        </p>
      </div>

      <div class="flex flex-wrap justify-center gap-8">
        <a href="#features" class="text-sm text-muted-foreground hover-elevate px-3 py-2" data-testid="link-footer-features">
          Features
        </a>
        <a href="#community" class="text-sm text-muted-foreground hover-elevate px-3 py-2" data-testid="link-footer-community">
          Community
        </a>
        <a href="#trust" class="text-sm text-muted-foreground hover-elevate px-3 py-2" data-testid="link-footer-trust">
          Trust & Safety
        </a>
        <a href="#" class="text-sm text-muted-foreground hover-elevate px-3 py-2 flex items-center gap-2" data-testid="link-footer-github">
          <svg class="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
          </svg>
          GitHub
        </a>
      </div>
    </div>

    <div class="mt-8 pt-8 border-t border-border text-center">
      <p class="text-sm text-muted-foreground" data-testid="text-footer-copyright">
        © {currentYear} Connect. Open source and community driven.
      </p>
    </div>
  </div>
</footer>

// local-connect-splash/client/src/components/Footer.tsx
import { SiGithub } from "react-icons/si";

export default function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-background border-t border-border py-12">
      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        <div className="flex flex-col md:flex-row justify-between items-center gap-8">
          <div className="flex flex-col items-center md:items-start gap-2">
            <div className="text-xl font-display font-bold" data-testid="text-footer-brand">
              Connect
            </div>
            <p className="text-sm text-muted-foreground text-center md:text-left" data-testid="text-footer-tagline">
              Real connections in the real world
            </p>
          </div>

          <div className="flex flex-wrap justify-center gap-8">
            <a href="#features" className="text-sm text-muted-foreground hover-elevate px-3 py-2" data-testid="link-footer-features">
              Features
            </a>
            <a href="#community" className="text-sm text-muted-foreground hover-elevate px-3 py-2" data-testid="link-footer-community">
              Community
            </a>
            <a href="#trust" className="text-sm text-muted-foreground hover-elevate px-3 py-2" data-testid="link-footer-trust">
              Trust & Safety
            </a>
            <a href="#" className="text-sm text-muted-foreground hover-elevate px-3 py-2 flex items-center gap-2" data-testid="link-footer-github">
              <SiGithub className="w-4 h-4" />
              GitHub
            </a>
          </div>
        </div>

        <div className="mt-8 pt-8 border-t border-border text-center">
          <p className="text-sm text-muted-foreground" data-testid="text-footer-copyright">
            © {currentYear} Connect. Open source and community driven.
          </p>
        </div>
      </div>
    </footer>
  );
}
