// local-connect-splash/client/src/pages/LandingPage.tsx
import Navigation from "@/components/Navigation";
import HeroSection from "@/components/HeroSection";
import ProblemSection from "@/components/ProblemSection";
import FeaturesGrid from "@/components/FeaturesGrid";
import UseCasesSection from "@/components/UseCasesSection";
import SocialProofSection from "@/components/SocialProofSection";
import TrustSection from "@/components/TrustSection";
import CTASection from "@/components/CTASection";
import Footer from "@/components/Footer";

export default function LandingPage() {
  return (
    <div className="min-h-screen">
      <Navigation />
      <HeroSection />
      <ProblemSection />
      <FeaturesGrid />
      <UseCasesSection />
      <SocialProofSection />
      <TrustSection />
      <CTASection />
      <Footer />
    </div>
  );
}

// client-svelte/src/external-resources/pages/LandingPage.svelte
<script lang="ts">
  import Navigation from '../components/Navigation.svelte';
  import HeroSection from '../components/HeroSection.svelte';
  import ProblemSection from '../components/ProblemSection.svelte';
  import FeaturesGrid from '../components/FeaturesGrid.svelte';
  import UseCasesSection from '../components/UseCasesSection.svelte';
  import SocialProofSection from '../components/SocialProofSection.svelte';
  import TrustSection from '../components/TrustSection.svelte';
  import CTASection from '../components/CTASection.svelte';
  import Footer from '../components/Footer.svelte';
</script>

<div class="min-h-screen">
  <Navigation />
  <HeroSection />
  <ProblemSection />
  <FeaturesGrid />
  <UseCasesSection />
  <SocialProofSection />
  <TrustSection />
  <CTASection />
  <Footer />
</div>
